language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
dist: xenial

before_install:
  - pip install --upgrade pip
  - pip install poetry

install:
  - poetry install -v
  - pre-commit install-hooks

cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit

script:
  - pre-commit run --all-files
  - pytest --cov-report=xml tests/
