language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
dist: xenial

before_install:
  - pip install --upgrade pip
  - pip install poetry

install:
  - poetry install -v

cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit

jobs:
  include:
    - stage: lint
      python: "3.6"
      script: pre-commit run --all-files

script:
  - pytest --cov-report xml tests
  - bash <(curl -s https://codecov.io/bash) -cF python
